version: '3'

services:
  minecraft-server:
    build:
      context: .
    ports:
      - 25565:25565
      - 25575:25575
      - 19132:19132/udp
    container_name: ${CONTAINER_NAME}
    volumes:
      - .minecraft-server:/minecraft-server
    stdin_open: true
    tty: true

volumes:
  minecraft-server:
