version: '3'

services:
  minecraft-server:
    build:
      context: .
    ports:
      - 25565:25565
      - 25575:25575
    container_name: ${CONTAINER_NAME}
    volumes:
      - minecraft-server:/minecraft-server

volumes:
  minecraft-server: